### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by neolectron** [tomhicks/react-audible-debug#1]
Hi,

I'm having a problem using your hook in the root element of my NextJs app.

I'm encountering this warning from chrome :
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.  https://goo.gl/7K7WLu`.

**Comment by tomhicks** [comment]
Hi, thanks for the issue.

You might need to switch the `enabled` flag from false to true after some navigation or button click or something.

Try putting a button on the page that switches a state value from false to true that you pass into the hook. It's a bit annoying but you could make a position:fixed button that only shows in dev mode that lets you enable/disable it.
